### ISSUE TITLE
--auto-delete 参数

### ISSUE THREAD

**Issue by stop-bullshit** [chyroc/icloudgo#10]
请问这个参数的意思是
从iCloud下载到本地后从iCloud删除吗?

**Comment by chyroc** [comment]
对

**Comment by chyroc** [comment]
不是，这个是获取 icloud 最近删除文件夹的数据，把之前同步过，但是现在已经在 icloud 删了的数据给删掉

**Comment by stop-bullshit** [comment]
那就好 我给我整不会了  Readme 那个英文注释有点歧义
