### ISSUE TITLE
no docker arm64 support 

### ISSUE THREAD

**Issue by 1Jo1** [chyroc/icloudgo#12]
when I run the docker image on aarch64 I'm getting this error 
```docker: no matching manifest for linux/arm64/v8 in the manifest list entries```

**Comment by chyroc** [comment]
use `0.20.1`, which support `linux/arm64/v8`

docker pull ghcr.io/chyroc/icloud-photo-cli:0.20.1

**Comment by 1Jo1** [comment]
thanks it works now :)
