### ISSUE TITLE
is it working with random file name?

### ISSUE THREAD

**Issue by czwen** [chyroc/icloudgo#3]
hi, the project is awesome. but i have some question.. 

is it working with random file name?
after download,file name is ARs0fhovjV2QqSHN3EdBs9bpG6a2.MOV 

is it possible files group by date using folder? 
like 2022/02/22/ARs0fhovjV2QqSHN3EdBs9bpG6a2.MOV 

last one , why some 1kb files downloaded?
i think it happend on when continuted download.

thansks.

**Comment by chyroc** [comment]
first issue,
```
is it possible files group by date using folder?
like 2022/02/22/ARs0fhovjV2QqSHN3EdBs9bpG6a2.MOV
```


use 0.10.0 version , and add param `--fs 2006/01/02`

**Comment by chyroc** [comment]
second issue
```
why some 1kb files downloaded?
i think it happend on when continuted download.
```

1kb files is tmp file, now, it moevd to `<output>/.tmp` dir

**Comment by czwen** [comment]
amazing..my pr is almost ready

**Comment by czwen** [comment]
1kb file occured again. 
download.db  photo_asset  status filed most is 1, but there are 70% 1kb files downloaded 

$ find . -type f | wc -l
34391

$ du -sh *
786M	2016
15M	2017
115M	2018
853M	2019
4.8M	2020
761M	2021
75G	2022
15G	2023

<img width="679" alt="image" src="https://user-images.githubusercontent.com/3235796/222626133-075f9696-c17a-4b0f-a038-ac6731b8c7c1.png">

**Comment by chyroc** [comment]
try 0.12.0
