### ISSUE TITLE
最新的0.12版docker镜像file-structure参数无效

### ISSUE THREAD

**Issue by best1000** [chyroc/icloudgo#6]
Status: Downloaded newer image for ghcr.io/chyroc/icloud-photo-cli:0.12
Incorrect Usage: flag provided but not defined: -file-structure

NAME:
   icloud-photo-cli download

USAGE:
   icloud-photo-cli download command [command options] [arguments...]

DESCRIPTION:
   download photos

COMMANDS:
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --username value, -u value                          apple id username [$ICLOUD_USERNAME]
   --password value, -p value                          apple id password [$ICLOUD_PASSWORD]
   --cookie-dir value, -c value                        cookie dir [$ICLOUD_COOKIE_DIR]
   --domain value, -d value                            icloud domain(com,cn) (default: com) [$ICLOUD_DOMAIN]
   --output value, -o value                            output dir (default: "./iCloudPhotos") [$ICLOUD_OUTPUT]
   --album value, -a value                             album name, if not set, download all albums [$ICLOUD_ALBUM]
   --folder-structure 2006, --fs 2006                  support: 2006(year), `01`(month), `02`(day), `15`(24-hour), `03`(12-hour), `04`(minute), `05`(second), example: `2006/01/02`, default is `/` (default: "/") [$ICLOUD_FOLDER_STRUCTURE]
   --stop-found-num stop-found-num, -s stop-found-num  stop download when found stop-found-num photos have been downloaded (default: 0) [$ICLOUD_STOP_FOUND_NUM]
   --thread-num value, -t value                        thread num, if not set, means 1 (default: 1) [$ICLOUD_THREAD_NUM]
   --auto-delete, --ad                                 auto delete photos after download (default: true) [$ICLOUD_AUTO_DELETE]
   --help, -h                                          show help
2023/04/09 13:07:02 flag provided but not defined: -file-structure

**Comment by best1000** [comment]
还有在下载照片时似乎没有下载live photo对应的mov文件，不知道是否需要调整什么参数

**Comment by chyroc** [comment]
file 这个参数用 v0.13.0
